### PR TITLE
Add tag functionality to blog posts

### LINKED ISSUE #47: Add tag functionality to website posts
**Is your feature request related to a problem? Please describe.**
If/when we start producing more tags, it'll be very hard to search through them all to find what we want. 

**Describe the solution you'd like**
I would like authors to be able to add tags to their post which can then be used to filter posts by that tag. 

**Describe alternatives you've considered**
Potentially a search bar to let users search specifically for the words they want. 

**Additional context**
Nothing other than I've already done this before so I know it's possible and works nicely.

### PR DESCRIPTION
**Pull request by benslv**
(closes #47)

Tags can be added to a post by including them as part of the post's frontmatter.

```md
---
path: "/blog/tagged-post-example"
date: "2021-11-07"
author: "Ben Silverman"
title: "This post shows off the new tag feature!"
tags: ["post", "example"]
---
```

Tags are rendered in a section at the top of each blog post, as a series of clickable links.

image

Clicking on a tag here takes the user to a page containing all of the posts with that tag, sorted by most recent.

image

Clicking on *View all tags* takes the user to a page display all the possible tags they can view, as well as how many posts use the tag.

image

### CODE REVIEW

**Comment by Sciencentistguy** [comment]
I don't completely love the way the tags are shown. It's a bit in-your-face.

Could we have something like how gmail does it? Smaller, and possible next to or just under the title?

image

Also the "view all tags" page needs a little bit more styling IMO.

**Comment by benslv** [comment]
Can take a look at a different design, yeah. Will post here.

**Comment by benslv** [comment]
How about this?

image

**Comment by Sciencentistguy** [comment]
I think that looks way better. Can you apply the same styling (boxes, hover behavior etc) to the "all tags" page as well? It looks like it just hasn't been styled :sweat_smile: 

image

**Comment by benslv** [comment]
Yeah I'll make that page look the same with those rectangular tag links, sure

**Comment by benslv** [comment]
Have made it look like this now

image

**Comment by benslv** [comment]
Will look into (probably) sorting them by most common but that's not something I can do in graphql and I have food I need to take out of the oven so I can't do it now

**Review by Sciencentistguy — APPROVED** [review]
LGTM

**Pull request merged**
