### PR TITLE
Update committee with new members

### PR DESCRIPTION
**Pull request by benslv**
Still waiting on photos from a few people, but I've updated the site anyway so their names are listed on there now.

### CODE REVIEW

**Comment by tomoneill19** [comment]
@benslv I've added a commit to this pull to reorder the committee list according to the new ordering the constitution. Otherwise it looks all fine.

**Review by tomoneill19 — COMMENTED** [review]
Will leave for @Sciencentistguy to approve as I've made changes. Seems good in principle.

**Review by tomoneill19 — COMMENTED** [review]
Tested locally at this commit. Seems to have updated properly.

**Review by Sciencentistguy — APPROVED** [review]
LGTM

**Comment by Sciencentistguy** [comment]
actually, this needs rebasing. i'll do that and merge

**Pull request merged**
